In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
x

array([1, 2, 3, 4, 5])

In [4]:
x.dtype

dtype('int32')

In [5]:
x.shape

(5,)

In [6]:
len(x)

5

In [7]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
y.shape

(4, 3)

In [9]:
y.dtype

dtype('int32')

In [10]:
y.size

12

In [11]:
type(x)

numpy.ndarray

In [12]:
type(y)

numpy.ndarray

In [13]:
x = np.array([1,2,'world'])

In [14]:
type(x)

numpy.ndarray

In [15]:
x.dtype

dtype('<U11')

In [16]:
x = np.array([1.5,2.2,3.7], dtype = np.int64)

In [17]:
x

array([1, 2, 3], dtype=int64)

In [18]:
np.save('my_array',x)

In [19]:
x = np.load('my_array.npy')

In [20]:
x

array([1, 2, 3], dtype=int64)

In [21]:
# numpy zeroes
X = np.zeros((3,4))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
print("dtype",X.dtype)

dtype float64


In [23]:
# ones matrix
X = np.ones((4,5))
X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
X =np.full((4,5),5)
X

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [25]:
# identity matrix
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# diagonal matrix
X = np.diag([10,20,30,50])
X

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])

In [27]:
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
X = np.arange(4,10)
X

array([4, 5, 6, 7, 8, 9])

In [29]:
X = np.arange(1,10,3)
X

array([1, 4, 7])

In [30]:
x = np.linspace(0,25,10)
x

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [31]:
x = np.linspace(0,25,10,endpoint=False)
x

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

In [32]:
# reshaping
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
x = np.reshape(x,(4,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
x = np.reshape(x,(10,2))
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [35]:
# method chaining
x = np.linspace(0,50,10,endpoint = False).reshape(5,2)
x

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

In [36]:
# numpy arrays containing random numbers

In [37]:
# random number between 0 and 1,0 inclusive and 1 exclusive
X = np.random.random((3,3))
print(X)

[[0.87719358 0.39153101 0.77516984]
 [0.37459027 0.21587581 0.12519972]
 [0.99508956 0.92312447 0.01917612]]


In [38]:
X = np.random.randint(4,15,(3,2))# 4 to 15,3x2
print(X)

[[ 8  9]
 [11 14]
 [ 8  4]]


In [39]:
# random number from probability distributions
X = np.random.normal(0,0.1,size = (1000,1000))# mean and standard deviation
X

array([[ 0.11265957, -0.02565407,  0.03769432, ..., -0.01352009,
        -0.08687844,  0.09038743],
       [-0.00278871, -0.09664529,  0.00930365, ...,  0.01008   ,
        -0.20323076, -0.02920266],
       [-0.16325154,  0.00576242, -0.10543541, ..., -0.10570415,
        -0.15643618, -0.02737118],
       ...,
       [-0.0272844 ,  0.03631178, -0.02858033, ..., -0.02186299,
         0.0108062 ,  0.03714531],
       [-0.01297196, -0.00901213, -0.13916462, ...,  0.06229539,
        -0.00102178,  0.09123211],
       [ 0.00599782,  0.16664401,  0.0995997 , ..., -0.17363424,
         0.00361649, -0.00801812]])

# Accessing , Deleting and Inserting

In [40]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [41]:
# positive indices

In [42]:
x[0]

1

In [43]:
x[1]

2

In [44]:
x[3]

4

In [45]:
# negative indices
print(x[-5])
print(x[-4])

1
2


In [46]:
x[3] = 20
x

array([ 1,  2,  3, 20,  5])

In [47]:
X = np.arange(1,10).reshape(3,3)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
X[0,0]

1

In [49]:
X[0,1]

2

In [50]:
X[2,2]

9

In [51]:
X[0,0]=20
X

array([[20,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [52]:
# add,delete
# for rank 1 access is not required
#axis 0 rows axis 1 columns
Y = np.arange(1,10).reshape(3,3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
W = np.delete(Y,0,axis = 0)
W

array([[4, 5, 6],
       [7, 8, 9]])

In [54]:
V = np.delete(Y,[0,2],axis = 1)
print(V)

[[2]
 [5]
 [8]]


In [55]:
# append to add
X = np.array([1,2,3,4,5])
print(X)
x = np.append(x,6)
print(x)

[1 2 3 4 5]
[ 1  2  3 20  5  6]


In [56]:
Y = np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
w = np.append(Y,[[10, 11, 12]],axis = 0)
print(w)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [58]:
v = np.append(Y,[[10], [11], [12]],axis = 1)
print(v)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [59]:
# insert
x = np.array([1,2,3,7,78])
print(x)

[ 1  2  3  7 78]


In [60]:
w = np.insert(x,1,[4,5,6],axis = 0)
print(w)

[ 1  4  5  6  2  3  7 78]


In [61]:
Y = np.array([[1, 2, 3], [7, 8, 9]])
print(Y)


[[1 2 3]
 [7 8 9]]


In [62]:
W = np.insert(Y, 1, [4,5,6],axis = 0)
W

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
V = np.insert(Y, 1, [[4],[5],[6]],axis = 0)
V

array([[1, 2, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6],
       [7, 8, 9]])

In [64]:
# stacking
x = np.array([1,2])
print(x)

[1 2]


In [65]:
y = np.array([[3,4], [5,6]])
print(y)

[[3 4]
 [5 6]]


In [66]:
z = np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [67]:
z = np.hstack((y,x.reshape(2,1)))
print(z)

[[3 4 1]
 [5 6 2]]


# slicing

In [68]:
# 1. ndarray[start:end]
# 2. ndarray[start:]
# 3. ndarray[:end]

In [70]:
X = np.arange(1,21).reshape(4,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [71]:
z = X[1:4, 2:5]
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [72]:
z = X[1:, 2:]
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [73]:
z = X[:3, 2:]
z

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [75]:
z = X[:,2]
z

array([ 3,  8, 13, 18])

In [77]:
z = X[:,2:3]
z

array([[ 3],
       [ 8],
       [13],
       [18]])

# slicing creates view of the originial variable

In [79]:
z = X[1:, 2:].copy()
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [81]:
indices = np.array([1,3])
indices

array([1, 3])

In [82]:
z = X[:, indices]
z

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19]])

In [83]:
np.diag(X)

array([ 1,  7, 13, 19])

In [84]:
# above main diagonal
z = np.diag(X, k = 1)
z

array([ 2,  8, 14, 20])

In [85]:
# below main diagonal
z = np.diag(X, k = -1)
z

array([ 6, 12, 18])

In [86]:
# extract unique 
z =np.unique(X)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# boolean indexing

In [87]:
X = np.arange(25).reshape(5,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
print(X[X>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [89]:
print(X[X<=17])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [90]:
X[(X>10)&(X<17)] = -1
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [94]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
print(np.intersect1d(x,y))

print(np.union1d(x,y))

print(np.setdiff1d(x,y))

[2 4]
[1 2 3 4 5 6 7 8]
[1 3 5]


In [95]:
np.sort(y)

array([2, 4, 6, 7, 8])

In [98]:
X =np.random.randint(1,11,size = (5,5))
X

array([[ 3,  3,  3,  6,  7],
       [ 3,  7,  6,  4,  1],
       [ 9,  5,  6,  9,  5],
       [ 1,  8, 10,  2,  4],
       [ 2,  3,  7,  8,  1]])

In [99]:
X.sort()

In [100]:
np.sort(X)

array([[ 3,  3,  3,  6,  7],
       [ 1,  3,  4,  6,  7],
       [ 5,  5,  6,  9,  9],
       [ 1,  2,  4,  8, 10],
       [ 1,  2,  3,  7,  8]])

In [101]:
np.sort(X, axis = 0)

array([[ 1,  2,  3,  6,  7],
       [ 1,  2,  3,  6,  7],
       [ 1,  3,  4,  7,  8],
       [ 3,  3,  4,  8,  9],
       [ 5,  5,  6,  9, 10]])

In [102]:
np.sort(X, axis = 1)

array([[ 3,  3,  3,  6,  7],
       [ 1,  3,  4,  6,  7],
       [ 5,  5,  6,  9,  9],
       [ 1,  2,  4,  8, 10],
       [ 1,  2,  3,  7,  8]])